# Generated by Django 3.1.2 on 2021-02-09 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0005_sessionmodified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SessionModified',
        ),
    ]
