# Generated by Django 3.1.2 on 2021-02-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0007_auto_20210209_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='savesession',
            name='device_family',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savesession',
            name='device_os',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
