# Generated by Django 3.1.2 on 2021-02-09 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0008_auto_20210209_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savesession',
            old_name='device_os',
            new_name='device_browser',
        ),
    ]
