# Generated by Django 3.1.2 on 2021-02-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0010_savesession_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savesession',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
