# Generated by Django 3.1.2 on 2021-02-09 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0011_auto_20210209_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savesession',
            old_name='date_created',
            new_name='login',
        ),
        migrations.AddField(
            model_name='savesession',
            name='logout',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 9, 15, 3, 11, 702666)),
        ),
    ]
